import "./globals.css";
import type { Metadata } from "next";
import { Inter, Rubik_Burned, Chakra_Petch } from "next/font/google";
import ConvexClientProvider from "./ConvexClientProvider";

export const font = Chakra_Petch({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-chakra",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.variable}>
        <ConvexClientProvider>{children}</ConvexClientProvider>
      </body>
    </html>
  );
}
